<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::bootSoftDeletes();
        static::deleted(function($product){
            $product->suppliers()->delete();
            $product->supplierpivot()->delete();
        });
    }

    protected $fillable = ["name", "description", "quantity"];

    public function orders(){
        return $this->belongsToMany(\App\Models\Order::class, "order_details", "product_id", "order_id");
    }

    public function suppliers(){
        return $this->belongsToMany(\App\Models\Supplier::class, "supplier_products", "product_id", "supply_id");
    }

    public function supplierpivot(){
        return $this->hasMany(\App\Models\SupplierProduct::class, "product_id");
    }
}
